"use strict";
// National-expansion note: this is the dataset that grows. Each plant record
// is the unit of geographic data. See CLAUDE.md before reshaping these fields.
const plants = [
{id:"aquatic-milkweed",common:"Aquatic milkweed",sci:"Asclepias perennis",layer:"middle",height:[18,36],spread:[12,24],bloom:[4,5,6,7,8,9,10],sun:["full","part"],moist:["average","wet"],soil:["clay","loam","unknown"],color:"white",roles:{bees:6,butterflies:8,monarchs:10,hummingbirds:1,cardinals:1,biodiversity:9},tags:["monarch host","nectar","wet soil","long bloom"],native:true,tidy:true,deer:false,pet:true,aggressive:false,squirrel:0,conditions:["rainGarden","heavyClay"],notes:"Houston-relevant milkweed for moist beds and rain-garden edges; primary role is monarch host support."},
{id:"green-milkweed",common:"Green milkweed",sci:"Asclepias viridis",layer:"middle",height:[12,30],spread:[12,18],bloom:[4,5,6],sun:["full"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"green",roles:{bees:6,butterflies:8,monarchs:10,hummingbirds:1,cardinals:1,biodiversity:8},tags:["monarch host","spring host","nectar"],native:true,tidy:true,deer:false,pet:true,aggressive:false,squirrel:0,conditions:["urbanHeat","heavyClay"],notes:"Good spring host option for monarchs in sunny Gulf Coast beds; wants drainage better than a wet swale."},
{id:"gulf-penstemon",common:"Gulf Coast penstemon",sci:"Penstemon tenuis",layer:"front",height:[12,24],spread:[12,18],bloom:[3,4,5],sun:["full","part"],moist:["average","wet"],soil:["clay","loam","unknown"],color:"lavender",roles:{bees:9,butterflies:4,monarchs:1,hummingbirds:4,cardinals:1,biodiversity:8},tags:["early bees","spring bloom","tidy edging"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["standard","rainGarden","heavyClay"],notes:"Compact spring bee plant and useful front/middle transition for a tidy Houston native bed."},
{id:"lanceleaf-coreopsis",common:"Lanceleaf coreopsis",sci:"Coreopsis lanceolata",layer:"front",height:[12,24],spread:[12,18],bloom:[4,5,6,7],sun:["full","part"],moist:["dry","average"],soil:["loam","sandy","clay","unknown"],color:"yellow",roles:{bees:8,butterflies:6,monarchs:2,hummingbirds:1,cardinals:2,biodiversity:8},tags:["early nectar","pollen","tidy edging"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:1,conditions:["standard","urbanHeat","coastalExposure"],notes:"Durable early-to-summer color; repeat in drifts for a legible front-yard look."},
{id:"frogfruit",common:"Texas frogfruit",sci:"Phyla nodiflora",layer:"front",height:[3,8],spread:[18,36],bloom:[4,5,6,7,8,9,10,11],sun:["full","part"],moist:["dry","average","wet"],soil:["clay","loam","sandy","unknown"],color:"white",roles:{bees:8,butterflies:7,monarchs:2,hummingbirds:1,cardinals:1,biodiversity:9},tags:["groundcover","long bloom","small bees","coastal tolerant"],native:true,tidy:true,deer:false,pet:false,aggressive:true,squirrel:0,conditions:["urbanHeat","rainGarden","coastalExposure","heavyClay"],notes:"Low living mulch with very long bloom; can spread, so edge it for tidy beds."},
{id:"indian-blanket",common:"Indian blanket",sci:"Gaillardia pulchella",layer:"front",height:[12,24],spread:[12,18],bloom:[5,6,7,8,9],sun:["full"],moist:["dry","average"],soil:["sandy","loam","unknown"],color:"red-yellow",roles:{bees:7,butterflies:7,monarchs:3,hummingbirds:1,cardinals:3,biodiversity:7},tags:["summer nectar","seed heads","coastal tolerant"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:1,conditions:["urbanHeat","coastalExposure"],notes:"Heat-tolerant color for sunny, better-drained beds; helpful where the design needs a bright Gulf Coast look."},
{id:"mealy-blue-sage",common:"Mealy blue sage",sci:"Salvia farinacea",layer:"middle",height:[24,36],spread:[18,24],bloom:[5,6,7,8,9,10],sun:["full","part"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"blue",roles:{bees:9,butterflies:6,monarchs:3,hummingbirds:5,cardinals:1,biodiversity:9},tags:["bees","long bloom","heat humidity","aromatic edge"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["standard","urbanHeat","heavyClay"],notes:"Long-blooming blue verticals for bees and general pollinator continuity."},
{id:"scarlet-sage",common:"Scarlet sage",sci:"Salvia coccinea",layer:"middle",height:[18,36],spread:[18,24],bloom:[5,6,7,8,9,10,11],sun:["full","part"],moist:["average"],soil:["loam","sandy","clay","unknown"],color:"red",roles:{bees:6,butterflies:6,monarchs:2,hummingbirds:9,cardinals:2,biodiversity:8},tags:["hummingbirds","red flowers","long bloom","aromatic edge"],native:true,tidy:true,deer:false,pet:false,aggressive:false,squirrel:0,conditions:["standard","urbanHeat"],notes:"Red tubular flowers make this a strong hummingbird bridge through Houston's warm season."},
{id:"turks-cap",common:"Turk's cap",sci:"Malvaviscus arboreus var. drummondii",layer:"back",height:[36,96],spread:[36,72],bloom:[5,6,7,8,9,10,11],sun:["part","shade","full"],moist:["dry","average","wet"],soil:["clay","loam","sandy","unknown"],color:"red",roles:{bees:5,butterflies:6,monarchs:2,hummingbirds:10,cardinals:8,biodiversity:9},tags:["hummingbirds","berries","cover","shade"],native:true,tidy:false,deer:false,pet:false,aggressive:true,squirrel:3,conditions:["standard","rainGarden","heavyClay"],notes:"High-value hummingbird and bird shrub for part shade; can get large, so use as a back anchor or thicket plant."},
{id:"cardinal-flower",common:"Cardinal flower",sci:"Lobelia cardinalis",layer:"middle",height:[24,48],spread:[12,18],bloom:[7,8,9,10],sun:["part","shade","full"],moist:["average","wet"],soil:["clay","loam","unknown"],color:"red",roles:{bees:4,butterflies:5,monarchs:2,hummingbirds:10,cardinals:1,biodiversity:8},tags:["hummingbirds","red flowers","wet soil","fall nectar"],native:true,tidy:true,deer:false,pet:true,aggressive:false,squirrel:0,conditions:["rainGarden","heavyClay"],notes:"Top choice for moist shade or rain-garden edges when the hummingbird goal is selected."},
{id:"coral-honeysuckle",common:"Coral honeysuckle",sci:"Lonicera sempervirens",layer:"back",height:[48,120],spread:[36,72],bloom:[3,4,5,6,7,8],sun:["full","part"],moist:["average"],soil:["loam","clay","unknown"],color:"red",roles:{bees:5,butterflies:5,monarchs:1,hummingbirds:10,cardinals:7,biodiversity:8},tags:["hummingbirds","vine","berries","spring bloom"],native:true,tidy:true,deer:false,pet:false,aggressive:false,squirrel:2,conditions:["standard","heavyClay"],notes:"Native vine for fence/trellis layers; supports hummingbirds early and birds later."},
{id:"crossvine",common:"Crossvine",sci:"Bignonia capreolata",layer:"back",height:[72,240],spread:[48,120],bloom:[3,4,5],sun:["full","part"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"orange",roles:{bees:5,butterflies:4,monarchs:1,hummingbirds:9,cardinals:3,biodiversity:6},tags:["hummingbirds","vine","spring bloom","evergreen cover"],native:true,tidy:false,deer:true,pet:false,aggressive:true,squirrel:1,conditions:["urbanHeat","heavyClay"],notes:"Large native vine for strong structures; too vigorous for a tiny tidy bed."},
{id:"blue-mistflower",common:"Blue mistflower",sci:"Conoclinium coelestinum",layer:"middle",height:[18,36],spread:[18,36],bloom:[8,9,10,11],sun:["part","shade","full"],moist:["average","wet"],soil:["clay","loam","unknown"],color:"blue",roles:{bees:7,butterflies:10,monarchs:7,hummingbirds:1,cardinals:1,biodiversity:9},tags:["late nectar","butterflies","monarch nectar","fall bloom"],native:true,tidy:false,deer:false,pet:false,aggressive:true,squirrel:0,conditions:["rainGarden","heavyClay"],notes:"Excellent late butterfly nectar; spreads, so contain it in tidy front-yard designs."},
{id:"fall-obedient",common:"Fall obedient plant",sci:"Physostegia virginiana",layer:"middle",height:[24,48],spread:[18,30],bloom:[8,9,10],sun:["full","part"],moist:["average","wet"],soil:["clay","loam","unknown"],color:"pink",roles:{bees:8,butterflies:7,monarchs:5,hummingbirds:4,cardinals:1,biodiversity:8},tags:["fall nectar","bees","wet soil"],native:true,tidy:false,deer:true,pet:false,aggressive:true,squirrel:0,conditions:["rainGarden","heavyClay"],notes:"Good late-season nectar for moist Gulf Coast soils; can form expanding colonies."},
{id:"frostweed",common:"Frostweed",sci:"Verbesina virginica",layer:"back",height:[36,72],spread:[24,36],bloom:[8,9,10,11],sun:["part","shade"],moist:["average","wet"],soil:["clay","loam","unknown"],color:"white",roles:{bees:8,butterflies:9,monarchs:8,hummingbirds:1,cardinals:3,biodiversity:9},tags:["fall nectar","monarch nectar","shade","structure"],native:true,tidy:false,deer:false,pet:false,aggressive:true,squirrel:1,conditions:["standard","rainGarden","heavyClay"],notes:"Important fall nectar in part shade; best for larger beds or naturalized edges."},
{id:"rough-coneflower",common:"Rough coneflower",sci:"Rudbeckia grandiflora / spp.",layer:"middle",height:[24,48],spread:[18,24],bloom:[6,7,8,9],sun:["full","part"],moist:["dry","average"],soil:["clay","loam","unknown"],color:"yellow",roles:{bees:8,butterflies:7,monarchs:3,hummingbirds:1,cardinals:7,biodiversity:8},tags:["bees","seed heads","songbird seed","summer bloom"],native:true,tidy:true,deer:false,pet:false,aggressive:false,squirrel:2,conditions:["standard","urbanHeat","heavyClay"],notes:"Reliable summer pollinator plant; leaving seed heads adds songbird value."},
{id:"blazing-star",common:"Blazing star",sci:"Liatris spp.",layer:"middle",height:[24,48],spread:[12,18],bloom:[7,8,9],sun:["full"],moist:["dry","average","wet"],soil:["clay","loam","sandy","unknown"],color:"purple",roles:{bees:8,butterflies:9,monarchs:6,hummingbirds:2,cardinals:1,biodiversity:9},tags:["butterflies","bees","monarch nectar","vertical structure"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["standard","urbanHeat","rainGarden"],notes:"Strong vertical nectar plant for butterflies and bees; choose a locally sourced Gulf Coast-appropriate species."},
{id:"goldenrod",common:"Seaside / tall goldenrod",sci:"Solidago spp.",layer:"back",height:[36,72],spread:[18,36],bloom:[9,10,11],sun:["full","part"],moist:["dry","average","wet"],soil:["clay","loam","sandy","unknown"],color:"gold",roles:{bees:10,butterflies:8,monarchs:8,hummingbirds:1,cardinals:4,biodiversity:10},tags:["late nectar","monarch nectar","bees","keystone"],native:true,tidy:false,deer:true,pet:false,aggressive:true,squirrel:1,conditions:["standard","urbanHeat","coastalExposure","heavyClay"],notes:"Very high late-season pollinator value; use compact species or contained drifts for tidy sites."},
{id:"fall-aster",common:"Gulf Coast fall aster",sci:"Symphyotrichum spp.",layer:"middle",height:[18,36],spread:[18,30],bloom:[9,10,11],sun:["full","part"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"purple",roles:{bees:9,butterflies:8,monarchs:7,hummingbirds:1,cardinals:2,biodiversity:9},tags:["late nectar","bees","fall bloom","monarch nectar"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["standard","urbanHeat","heavyClay"],notes:"Late-season nectar bridge for bees and migrating butterflies."},
{id:"little-bluestem",common:"Little bluestem",sci:"Schizachyrium scoparium",layer:"back",height:[24,48],spread:[18,24],bloom:[8,9,10],sun:["full"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"green",roles:{bees:2,butterflies:4,monarchs:1,hummingbirds:1,cardinals:6,biodiversity:8},tags:["grass","overwintering habitat","seed heads","structure"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:1,conditions:["standard","urbanHeat","coastalExposure","heavyClay"],notes:"Warm-season grass for structure, nesting material, overwintering insects, and winter texture."},
{id:"gulf-muhly",common:"Gulf muhly",sci:"Muhlenbergia capillaris",layer:"back",height:[24,48],spread:[24,36],bloom:[9,10,11],sun:["full","part"],moist:["dry","average","wet"],soil:["clay","loam","sandy","unknown"],color:"pink",roles:{bees:1,butterflies:3,monarchs:1,hummingbirds:1,cardinals:5,biodiversity:7},tags:["grass","structure","coastal tolerant","winter texture"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:1,conditions:["standard","urbanHeat","rainGarden","coastalExposure"],notes:"Tidy ornamental native grass with Gulf Coast fit; provides structure more than nectar."},
{id:"inland-sea-oats",common:"Inland sea oats",sci:"Chasmanthium latifolium",layer:"middle",height:[24,42],spread:[18,30],bloom:[7,8,9,10],sun:["part","shade"],moist:["average","wet"],soil:["clay","loam","unknown"],color:"green",roles:{bees:1,butterflies:3,monarchs:1,hummingbirds:1,cardinals:6,biodiversity:7},tags:["shade grass","seed heads","structure","cover"],native:true,tidy:true,deer:true,pet:false,aggressive:true,squirrel:2,conditions:["standard","rainGarden","heavyClay"],notes:"Useful shade grass for cover and seed heads; self-sows in moist shade."},
{id:"beautyberry",common:"American beautyberry",sci:"Callicarpa americana",layer:"back",height:[48,96],spread:[48,96],bloom:[5,6,7],sun:["part","shade","full"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"pink",roles:{bees:6,butterflies:3,monarchs:1,hummingbirds:1,cardinals:10,biodiversity:8},tags:["berries","songbird food","cover","shrub"],native:true,tidy:true,deer:false,pet:false,aggressive:false,squirrel:4,conditions:["standard","urbanHeat","heavyClay"],notes:"Excellent bird shrub and nectar for small bees; berry value may also attract squirrels."},
{id:"yaupon",common:"Yaupon holly",sci:"Ilex vomitoria",layer:"back",height:[72,240],spread:[48,120],bloom:[3,4],sun:["full","part","shade"],moist:["dry","average","wet"],soil:["clay","loam","sandy","unknown"],color:"white",roles:{bees:6,butterflies:2,monarchs:1,hummingbirds:1,cardinals:10,biodiversity:8},tags:["berries","evergreen cover","songbird food","shrub"],native:true,tidy:true,deer:true,pet:true,aggressive:false,squirrel:4,conditions:["standard","rainGarden","coastalExposure","heavyClay"],notes:"Evergreen cover and winter berries for birds; use dwarf/maintained forms for front yards and verify pet risk."},
{id:"buttonbush",common:"Buttonbush",sci:"Cephalanthus occidentalis",layer:"back",height:[60,144],spread:[48,120],bloom:[6,7,8],sun:["full","part"],moist:["wet"],soil:["clay","loam","unknown"],color:"white",roles:{bees:8,butterflies:9,monarchs:4,hummingbirds:2,cardinals:7,biodiversity:9},tags:["wet soil","butterflies","bees","songbird food","shrub"],native:true,tidy:false,deer:false,pet:false,aggressive:true,squirrel:3,conditions:["rainGarden","heavyClay"],notes:"High-value wetland shrub for larger rain gardens; too big for small tidy beds."},
{id:"coralbean",common:"Coralbean",sci:"Erythrina herbacea",layer:"back",height:[36,72],spread:[36,60],bloom:[3,4,5],sun:["full","part"],moist:["dry","average"],soil:["sandy","loam","unknown"],color:"red",roles:{bees:3,butterflies:4,monarchs:1,hummingbirds:10,cardinals:2,biodiversity:6},tags:["hummingbirds","red flowers","spring bloom"],native:true,tidy:true,deer:true,pet:true,aggressive:false,squirrel:1,conditions:["urbanHeat","coastalExposure"],notes:"Early red tubular flowers for hummingbirds; seeds are toxic, so avoid where pets or children browse."},
{id:"passionflower",common:"Purple passionflower",sci:"Passiflora incarnata",layer:"back",height:[36,120],spread:[36,96],bloom:[5,6,7,8,9],sun:["full","part"],moist:["dry","average"],soil:["loam","sandy","clay","unknown"],color:"purple",roles:{bees:5,butterflies:10,monarchs:1,hummingbirds:1,cardinals:5,biodiversity:8},tags:["butterfly host","nectar","vine","fruit"],native:true,tidy:false,deer:false,pet:false,aggressive:true,squirrel:3,conditions:["standard","urbanHeat"],notes:"Host plant for Gulf fritillary and other passionflower butterflies; use only where a spreading vine is acceptable."}
,{id:"lemon-beebalm",common:"Lemon beebalm",sci:"Monarda citriodora",layer:"front",height:[12,30],spread:[12,18],bloom:[5,6,7,8],sun:["full","part"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"lavender",roles:{bees:9,butterflies:7,monarchs:2,hummingbirds:3,cardinals:1,biodiversity:8},tags:["bees","butterflies","aromatic edge","mint family","summer bloom"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["standard","urbanHeat","streetHellstrip","coastalExposure"],notes:"Aromatic Texas native annual/perennial used here as a pollinator-friendly seating-edge companion; passive plants alone should not be treated as mosquito control."}
,{id:"spotted-beebalm",common:"Spotted beebalm",sci:"Monarda punctata",layer:"middle",height:[18,36],spread:[18,24],bloom:[6,7,8,9],sun:["full","part"],moist:["dry","average"],soil:["sandy","loam","clay","unknown"],color:"pink",roles:{bees:10,butterflies:7,monarchs:3,hummingbirds:2,cardinals:1,biodiversity:8},tags:["bees","butterflies","aromatic edge","mint family","summer bloom"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["standard","urbanHeat","coastalExposure"],notes:"Aromatic mint-family native with strong bee value; included as a mosquito-aware comfort-edge option without promising bite prevention."}
,{id:"wax-myrtle",common:"Southern wax myrtle",sci:"Morella cerifera",layer:"back",height:[72,180],spread:[48,120],bloom:[3,4],sun:["full","part","shade"],moist:["average","wet"],soil:["clay","loam","sandy","unknown"],color:"green",roles:{bees:4,butterflies:2,monarchs:1,hummingbirds:1,cardinals:9,biodiversity:7},tags:["berries","evergreen cover","songbird food","shrub","open base","snake-aware candidate"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:4,conditions:["standard","rainGarden","coastalExposure","heavyClay"],notes:"Evergreen Gulf Coast bird shrub. In snake-aware mode, use as limbed-up/open-base structure rather than a dense thicket."}
,{id:"texas-kidneywood",common:"Texas kidneywood",sci:"Eysenhardtia texana",layer:"back",height:[48,120],spread:[36,72],bloom:[5,6,7,8,9],sun:["full","part"],moist:["dry","average"],soil:["clay","loam","sandy","unknown"],color:"white",roles:{bees:9,butterflies:6,monarchs:2,hummingbirds:1,cardinals:2,biodiversity:8},tags:["bees","small tree","open base","snake-aware candidate","summer bloom"],native:true,tidy:true,deer:true,pet:false,aggressive:false,squirrel:1,conditions:["standard","urbanHeat","heavyClay"],notes:"Excellent bee shrub/small tree in much of Texas; included as an open-base candidate with local Gulf Coast nursery/range verification needed."}
,{id:"prickly-pear",common:"Texas prickly pear",sci:"Opuntia engelmannii var. lindheimeri / spp.",layer:"front",height:[18,60],spread:[24,72],bloom:[4,5,6],sun:["full"],moist:["dry"],soil:["sandy","loam","clay","unknown"],color:"yellow",roles:{bees:7,butterflies:4,monarchs:1,hummingbirds:1,cardinals:3,biodiversity:6},tags:["bees","spiky edge","snake-aware candidate","dry soil","coastal tolerant"],native:true,tidy:true,deer:true,pet:true,aggressive:false,squirrel:1,conditions:["urbanHeat","streetHellstrip","coastalExposure"],notes:"Spiny native cactus candidate for hot, dry, visible edges only; keep away from narrow paths, children, and pets."}
,{id:"lemongrass",common:"Lemongrass",sci:"Cymbopogon citratus",layer:"middle",height:[36,60],spread:[36,48],bloom:[8,9,10],sun:["full"],moist:["average"],soil:["loam","sandy","unknown"],color:"green",roles:{bees:1,butterflies:1,monarchs:1,hummingbirds:1,cardinals:1,biodiversity:1},tags:["aromatic edge","snake-aware candidate","non-native companion","container candidate"],native:false,tidy:true,deer:true,pet:true,aggressive:false,squirrel:0,conditions:["urbanHeat","patioContainer"],notes:"Non-native aromatic companion candidate. Include only if native-only is off; do not treat as proven snake control."}
,{id:"rosemary",common:"Rosemary",sci:"Salvia rosmarinus",layer:"middle",height:[24,60],spread:[24,48],bloom:[2,3,4,5],sun:["full"],moist:["dry","average"],soil:["sandy","loam","unknown"],color:"blue",roles:{bees:5,butterflies:2,monarchs:1,hummingbirds:1,cardinals:1,biodiversity:3},tags:["aromatic edge","snake-aware candidate","non-native companion","bees"],native:false,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["urbanHeat","patioContainer","coastalExposure"],notes:"Non-native aromatic herb with bee value in bloom; needs sharp drainage in Houston humidity and is not proven snake control."}
,{id:"lavender",common:"Lavender",sci:"Lavandula spp.",layer:"front",height:[18,36],spread:[18,36],bloom:[5,6,7],sun:["full"],moist:["dry"],soil:["sandy","loam","unknown"],color:"purple",roles:{bees:5,butterflies:3,monarchs:1,hummingbirds:1,cardinals:1,biodiversity:3},tags:["aromatic edge","snake-aware candidate","non-native companion","bees"],native:false,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["urbanHeat","patioContainer"],notes:"Non-native aromatic herb; Houston heat/humidity and wet clay can be difficult, so use only in dry raised edges or containers."}
,{id:"society-garlic",common:"Society garlic",sci:"Tulbaghia violacea",layer:"front",height:[12,24],spread:[12,18],bloom:[5,6,7,8,9,10],sun:["full","part"],moist:["dry","average"],soil:["loam","sandy","clay","unknown"],color:"lavender",roles:{bees:4,butterflies:3,monarchs:1,hummingbirds:1,cardinals:1,biodiversity:3},tags:["aromatic edge","snake-aware candidate","non-native companion","tidy edging"],native:false,tidy:true,deer:true,pet:true,aggressive:false,squirrel:0,conditions:["standard","urbanHeat","patioContainer"],notes:"Non-native aromatic edging candidate; verify pet/allium risk and do not rely on it as snake control."}
,{id:"chives",common:"Chives / garlic chives",sci:"Allium schoenoprasum / tuberosum",layer:"front",height:[12,24],spread:[8,16],bloom:[4,5,6,7,8],sun:["full","part"],moist:["average"],soil:["loam","sandy","unknown"],color:"purple",roles:{bees:5,butterflies:2,monarchs:1,hummingbirds:1,cardinals:1,biodiversity:3},tags:["aromatic edge","snake-aware candidate","non-native companion","bees","tidy edging"],native:false,tidy:true,deer:true,pet:true,aggressive:false,squirrel:0,conditions:["standard","patioContainer"],notes:"Small aromatic allium companion; verify pet risk and deadhead garlic chives where reseeding is unwanted."}
,{id:"marigold",common:"Marigold",sci:"Tagetes spp.",layer:"front",height:[8,24],spread:[8,18],bloom:[5,6,7,8,9,10,11],sun:["full"],moist:["average"],soil:["loam","sandy","unknown"],color:"orange",roles:{bees:3,butterflies:3,monarchs:1,hummingbirds:1,cardinals:1,biodiversity:2},tags:["aromatic edge","snake-aware candidate","non-native companion","annual color","tidy edging"],native:false,tidy:true,deer:true,pet:false,aggressive:false,squirrel:0,conditions:["urbanHeat","patioContainer"],notes:"Non-native annual edge color sometimes claimed as a snake deterrent; use only as optional companion color, not as proven control."}


];
